---
- name: Install nginx
  dnf:
    name: nginx
    state: present
    update_cache: yes

- name: Enable and start nginx
  systemd:
    name: nginx
    state: started
    enabled: true

- name: Deploy custom index.html
  copy:
    src: index.html
    dest: /usr/share/nginx/html/index.html
    owner: root
    group: root
    mode: '0644'
  notify: Restart nginx